Try uncrustify report Update .gitlab-ci.yml file Update file .gitlab-ci.yml Update file .gitlab-ci.yml Update file .gitlab-ci.yml Update file .gitlab-ci.yml Update file .gitlab-ci.yml Update file .gitlab-ci.yml Update file uncrustify2codeclimate Update file uncrustify2codeclimate Update file uncrustify2codeclimate Update file uncrustify2codeclimate Update file uncrustify2codeclimate Update 2 files
- /.gitlab-ci.yml
- /uncrustify2codeclimate
Update 4 files

- /uncrustify2codeclimate
- /uncrustify-diff
- /.gitlab-ci.yml
- /dune/common/bitsetvector.hh
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update file .gitlab-ci.yml
Update .gitlab-ci.yml file
Update .gitlab-ci.yml file
Update file .gitlab-ci.yml
Update file bitsetvector.hh
Update file .gitlab-ci.yml
Update file uncrustify-diff
Update file .gitlab-ci.yml
Update file uncrustify-diff
Update file uncrustify-diff
Update file uncrustify-diff
Update file uncrustify-diff
Update file uncrustify-diff

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,93 +6,126 @@ include:
   - project: 'core/ci-config'
     ref: master
     file: 'config/common/master.yml'
-  - project: 'core/ci-config'
-    ref: master
-    file: 'jobs/common/master.yml'
+  # - project: 'core/ci-config'
+  #   ref: master
+  #   file: 'jobs/common/master.yml'
 
-before_script:
-  - . /duneci/bin/duneci-init-job
+stages:
+  - code_quality
 
-variables:
-  DUNECI_TEST_LABELS: quick
-  DUNE_TEST_EXPECTED_VC_IMPLEMENTATION: SSE2
-  PIP_DEFAULT_TIMEOUT: 0
-  # Note: DUNE_RUNNING_IN_CI only needed unti ci image updating fixed on gitlab
-  DUNECI_CMAKE_FLAGS: '-DDUNE_RUNNING_IN_CI=TRUE'
-  DUNE_LOG_LEVEL:     DEBUG
-
-ubuntu:20.04 gcc-9-17-expensive:
-  extends: .common
-  # This image has Vc
-  image: registry.dune-project.org/docker/ci/ubuntu:20.04
-  # allow expensive tests
-  variables:
-    DUNECI_CXXFLAGS: -mavx
-    DUNECI_TEST_LABELS: ""
-    DUNECI_TOOLCHAIN: gcc-9-17
-    DUNE_TEST_EXPECTED_VC_IMPLEMENTATION: AVX
-  # require AVX to properly test Vc
-  tags: [duneci, "iset:avx"]
-  # allowed to fail to e.g. do no hold up a merge when a runner supporting avx
-  # is unavailable
-  allow_failure: true
-
-ubuntu:20.04 gcc-9-17-nopython:
-  extends: .common
-  image: registry.dune-project.org/docker/ci/ubuntu:20.04
-  variables:
-    DUNECI_TOOLCHAIN:  gcc-9-17
-    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_Python3=TRUE'
-
-debian:11 clang-11-20-nobindings:
-  extends: .common
-  image: registry.dune-project.org/docker/ci/debian:11
-  variables:
-    DUNECI_TOOLCHAIN: clang-11-20
-    DUNECI_CMAKE_FLAGS: '-DDUNE_ENABLE_PYTHONBINDINGS=OFF'
-
-core-modules-test:
-  stage: downstream
-  variables:
-    CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
-    DUNECI_TEST_LABELS: ""
-  trigger:
-    project: infrastructure/dune-nightly-test
-    branch: core
-    strategy: depend
+workflow:
   rules:
-    - when: manual
-      allow_failure: false
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
+      when: never
+    - if: $CI_COMMIT_BRANCH
 
-full-system-test:
-  stage: downstream
-  variables:
-    CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
-    DUNECI_TEST_LABELS: ""
-  trigger:
-    project: infrastructure/dune-nightly-test
-    branch: master
-    strategy: depend
-  rules:
-    - when: manual
-      allow_failure: true
 
-# Check for spelling mistakes in text
-code-spelling-check:
-  stage: .pre
-  tags: [duneci]
-  image: registry.dune-project.org/docker/ci/debian:11
+# before_script:
+#   - . /duneci/bin/duneci-init-job
+
+# variables:
+#   DUNECI_TEST_LABELS: quick
+#   DUNE_TEST_EXPECTED_VC_IMPLEMENTATION: SSE2
+#   PIP_DEFAULT_TIMEOUT: 0
+#   # Note: DUNE_RUNNING_IN_CI only needed unti ci image updating fixed on gitlab
+#   DUNECI_CMAKE_FLAGS: '-DDUNE_RUNNING_IN_CI=TRUE'
+#   DUNE_LOG_LEVEL:     DEBUG
+
+# ubuntu:20.04 gcc-9-17-expensive:
+#   extends: .common
+#   # This image has Vc
+#   image: registry.dune-project.org/docker/ci/ubuntu:20.04
+#   # allow expensive tests
+#   variables:
+#     DUNECI_CXXFLAGS: -mavx
+#     DUNECI_TEST_LABELS: ""
+#     DUNECI_TOOLCHAIN: gcc-9-17
+#     DUNE_TEST_EXPECTED_VC_IMPLEMENTATION: AVX
+#   # require AVX to properly test Vc
+#   tags: [duneci, "iset:avx"]
+#   # allowed to fail to e.g. do no hold up a merge when a runner supporting avx
+#   # is unavailable
+#   allow_failure: true
+
+# ubuntu:20.04 gcc-9-17-nopython:
+#   extends: .common
+#   image: registry.dune-project.org/docker/ci/ubuntu:20.04
+#   variables:
+#     DUNECI_TOOLCHAIN:  gcc-9-17
+#     DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_Python3=TRUE'
+
+# debian:11 clang-11-20-nobindings:
+#   extends: .common
+#   image: registry.dune-project.org/docker/ci/debian:11
+#   variables:
+#     DUNECI_TOOLCHAIN: clang-11-20
+#     DUNECI_CMAKE_FLAGS: '-DDUNE_ENABLE_PYTHONBINDINGS=OFF'
+
+# core-modules-test:
+#   stage: downstream
+#   variables:
+#     CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
+#     DUNECI_TEST_LABELS: ""
+#   trigger:
+#     project: infrastructure/dune-nightly-test
+#     branch: core
+#     strategy: depend
+#   rules:
+#     - when: manual
+#       allow_failure: false
+
+# full-system-test:
+#   stage: downstream
+#   variables:
+#     CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
+#     DUNECI_TEST_LABELS: ""
+#   trigger:
+#     project: infrastructure/dune-nightly-test
+#     branch: master
+#     strategy: depend
+#   rules:
+#     - when: manual
+#       allow_failure: true
+
+# # Check for spelling mistakes in text
+# code-spelling-check:
+#   stage: .pre
+#   tags: [duneci]
+#   image: registry.dune-project.org/docker/ci/debian:11
+#   script:
+#   - codespell
+#     --ignore-words-list te,inout,incrementall,iif,\trun,referr,ba
+#     --skip pybind11
+
+# reuse:
+#   stage: .pre
+#   image:
+#     name: docker.io/fsfe/reuse:latest
+#     entrypoint: [""]
+#   tags: [duneci]
+#   before_script: ""
+#   script:
+#     - reuse lint
+
+# Verify code-formatting rules
+code-formatting-check:
+  stage: code_quality
+  image: registry.dune-project.org/docker/ci/debian:10
+  # variables:
+  #   GIT_STRATEGY: clone
   script:
-  - codespell
-    --ignore-words-list te,inout,incrementall,iif,\trun,referr,ba
-    --skip pybind11
-
-reuse:
-  stage: .pre
-  image:
-    name: docker.io/fsfe/reuse:latest
-    entrypoint: [""]
-  tags: [duneci]
-  before_script: ""
-  script:
-    - reuse lint
+  # Format all *.cc and *.hh files using the uncrustify tool
+  - git config --global --add safe.directory /builds/core/dune-common
+  - git status
+  - git diff --no-prefix remotes/origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} > target_diff.patch
+  - python3 uncrustify-diff --target-diff target_diff.patch --format diff         `find . -name "*.cc" -o -name "*.hh"`
+  - python3 uncrustify-diff --target-diff target_diff.patch --format code-climate `find . -name "*.cc" -o -name "*.hh"` > uncrustify-code-quality-report.json
+  - report=$(cat ./uncrustify-code-quality-report.json)
+  - |-
+    if [[ -n "$report" && "$report" != "[]" ]]; then
+      exit 1
+    fi
+  artifacts:
+    reports:
+      codequality: uncrustify-code-quality-report.json
